# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coef_liureg <- function(obj) {
    .Call(`_fastliu_coef_liureg`, obj)
}

covliucpp <- function(obj) {
    .Call(`_fastliu_covliucpp`, obj)
}

diagHcpp <- function(obj) {
    .Call(`_fastliu_diagHcpp`, obj)
}

hatcpp <- function(obj) {
    .Call(`_fastliu_hatcpp`, obj)
}

liuoptlamcpp <- function(obj) {
    .Call(`_fastliu_liuoptlamcpp`, obj)
}

liuregcpp <- function(Xmat, yvec, lambda, scale) {
    .Call(`_fastliu_liuregcpp`, Xmat, yvec, lambda, scale)
}

liustatscpp <- function(obj) {
    .Call(`_fastliu_liustatscpp`, obj)
}

predict_liureg <- function(obj, newdata) {
    .Call(`_fastliu_predict_liureg`, obj, newdata)
}

pressliucpp <- function(obj) {
    .Call(`_fastliu_pressliucpp`, obj)
}

